[build]
  command = "bun run build"
  functions = "out_functions"
  publish = "out_publish"
  base = "/"

[dev]
  command = "bun run dev"
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
